# common aliases
alias ls='ls -G' # ls with color
alias l='ls -G' 
alias ll='ls -lGh'
alias la='ls -laGh'
alias x='exit'
alias ..='cd ..'

# bash & cli
alias so='source'
alias tmux="TERM=screen-256color-bce tmux"
alias v='vim'
alias dotvim='cd ~/.vim'

# git
alias gs='git status'
alias gc='git commit'
alias ga='git add'
alias gd='git diff'
alias gco='git checkout'
alias gps='git push'
alias gpl='git pull'
alias gf='git fetch'
alias grh='git reset HEAD'
alias grb='git rebase'
