# enable Ctrl-S in vim
stty -ixon 

# use vim as standard command-line editor
export EDITOR=vim

# fancy bash start line
export PS1="[\u@\h] \W\[\033[32m\]\$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/')\[\033[00m\] $ "
