PLATFORM=$(uname)

if [[ "$PLATFORM" == 'Linux' ]]; then
  alias ls='ls --color=auto'
elif [[ "$PLATFORM" == 'Darwin' ]]; then
  alias ls='ls -G'
fi

# common aliases
alias l='ls' 
alias ll='l -lh'
alias la='l -lah'
alias x='exit'
alias ..='cd ..'

# bash & cli
alias so='source'
alias tmux="TERM=screen-256color-bce tmux"
alias v='vim'
alias dotvim='cd ~/.vim'

# git
alias gs='git status'
alias gc='git commit'
alias ga='git add'
alias gd='git diff'
alias gl='git log'
alias gf='git fetch'
alias gco='git checkout'
alias gps='git push'
alias gpl='git pull'
alias grh='git reset HEAD'
alias grb='git rebase'
